"""MVP auth, location, notification and blood-bag lifecycle additions."""
from alembic import op
import sqlalchemy as sa
revision="0002_mvp_security_bags"; down_revision="0001_initial_erd"; branch_labels=None; depends_on=None
def upgrade():
 op.add_column("users",sa.Column("date_of_birth",sa.Date(),nullable=True)); op.add_column("users",sa.Column("email_verified",sa.Boolean(),nullable=False,server_default=sa.false())); op.add_column("hospitals",sa.Column("latitude",sa.Float(),nullable=True)); op.add_column("hospitals",sa.Column("longitude",sa.Float(),nullable=True)); op.add_column("donors",sa.Column("latitude",sa.Float(),nullable=True)); op.add_column("donors",sa.Column("longitude",sa.Float(),nullable=True)); op.add_column("donors",sa.Column("is_available",sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table("refresh_tokens",sa.Column("token_id",sa.String(50),primary_key=True),sa.Column("user_id",sa.String(50),sa.ForeignKey("users.user_id",ondelete="CASCADE"),nullable=False),sa.Column("token_hash",sa.String(128),unique=True,nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("replaced_by_token_id",sa.String(50)))
 op.create_table("password_reset_tokens",sa.Column("token_id",sa.String(50),primary_key=True),sa.Column("user_id",sa.String(50),sa.ForeignKey("users.user_id",ondelete="CASCADE"),nullable=False),sa.Column("token_hash",sa.String(128),unique=True,nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("used_at",sa.DateTime(timezone=True)),sa.Column("attempts",sa.Integer(),nullable=False,server_default="0"))
 op.create_table("device_tokens",sa.Column("device_token_id",sa.String(50),primary_key=True),sa.Column("user_id",sa.String(50),sa.ForeignKey("users.user_id",ondelete="CASCADE"),nullable=False),sa.Column("token",sa.String(500),unique=True,nullable=False),sa.Column("provider",sa.String(40),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("blood_bag_status_history",sa.Column("history_id",sa.String(50),primary_key=True),sa.Column("blood_bag_id",sa.String(50),sa.ForeignKey("blood_bags.blood_bag_id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("changed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("changed_by_user_id",sa.String(50),sa.ForeignKey("users.user_id"),nullable=False),sa.Column("location",sa.String(255)),sa.Column("notes",sa.Text()))
def downgrade():
 for t in ["blood_bag_status_history","device_tokens","password_reset_tokens","refresh_tokens"]: op.drop_table(t)
 for t,c in [("donors","is_available"),("donors","longitude"),("donors","latitude"),("hospitals","longitude"),("hospitals","latitude"),("users","email_verified"),("users","date_of_birth")]: op.drop_column(t,c)
