from __future__ import annotations
from abc import ABC,abstractmethod
from app.repositories.models import BloodBagRecord,BloodBagHistoryRecord
class BloodBagRepository(ABC):
 @abstractmethod
 async def get(self,id:str)->BloodBagRecord|None:...
 @abstractmethod
 async def list(self,bank_id:str|None=None)->list[BloodBagRecord]:...
 @abstractmethod
 async def create(self,r:BloodBagRecord)->BloodBagRecord:...
 @abstractmethod
 async def update(self,r:BloodBagRecord)->BloodBagRecord:...
 @abstractmethod
 async def add_history(self,r:BloodBagHistoryRecord)->BloodBagHistoryRecord:...
 @abstractmethod
 async def history(self,id:str)->list[BloodBagHistoryRecord]:...
 @abstractmethod
 async def get_by_qr(self,qr:str)->BloodBagRecord|None:...
