from abc import ABC, abstractmethod
from app.repositories.models import CaregiverAssignmentRecord

class CaregiverRepository(ABC):
    @abstractmethod
    async def create(self, record: CaregiverAssignmentRecord) -> CaregiverAssignmentRecord: ...
    @abstractmethod
    async def get_by_id(self, assignment_id: str) -> CaregiverAssignmentRecord | None: ...
    @abstractmethod
    async def list_for_user(self, user_id: str) -> list[CaregiverAssignmentRecord]: ...
    @abstractmethod
    async def list_for_hospital(self, hospital_id: str) -> list[CaregiverAssignmentRecord]: ...
    @abstractmethod
    async def update(self, record: CaregiverAssignmentRecord) -> CaregiverAssignmentRecord: ...
