from abc import ABC, abstractmethod
from app.repositories.models import DonorRecord, DonationRecord, DonationResponseRecord, ConsentRecord, DonationVoucherRecord

class DonorRepository(ABC):
    @abstractmethod
    async def get_by_id(self, donor_id: str) -> DonorRecord | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: str) -> DonorRecord | None: ...
    @abstractmethod
    async def create(self, donor: DonorRecord) -> DonorRecord: ...
    @abstractmethod
    async def update(self, donor: DonorRecord) -> DonorRecord: ...
    @abstractmethod
    async def list_all(self) -> list[DonorRecord]: ...
    @abstractmethod
    async def list_donations(self, donor_id: str) -> list[DonationRecord]: ...
    @abstractmethod
    async def create_donation(self, donation: DonationRecord) -> DonationRecord: ...
    @abstractmethod
    async def get_donation(self, donation_id: str) -> DonationRecord | None: ...
    @abstractmethod
    async def list_responses(self, donor_id: str) -> list[DonationResponseRecord]: ...
    @abstractmethod
    async def create_response(self, response: DonationResponseRecord) -> DonationResponseRecord: ...
    @abstractmethod
    async def create_consent(self, consent: ConsentRecord) -> ConsentRecord: ...
    @abstractmethod
    async def list_consents(self, donor_id: str) -> list[ConsentRecord]: ...
    @abstractmethod
    async def create_voucher(self, voucher: DonationVoucherRecord) -> DonationVoucherRecord: ...
    @abstractmethod
    async def get_voucher_by_donation(self, donation_id: str) -> DonationVoucherRecord | None: ...
