from abc import ABC, abstractmethod
from app.repositories.models import PaymentRecord

class PaymentRepository(ABC):
    @abstractmethod
    async def create(self, record: PaymentRecord) -> PaymentRecord: ...
    @abstractmethod
    async def get_by_id(self, payment_id: str) -> PaymentRecord | None: ...
    @abstractmethod
    async def list_for_request(self, blood_request_id: str) -> list[PaymentRecord]: ...
    @abstractmethod
    async def get_by_provider_order_id(self, provider_order_id: str) -> PaymentRecord | None: ...
    @abstractmethod
    async def update(self, record: PaymentRecord) -> PaymentRecord: ...
