class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'LifeLink',
      'login_title': 'Welcome Back',
      'login_subtitle': 'Sign in to continue saving lives',
      'email': 'Email Address',
      'password': 'Password',
      'sign_in': 'Sign In',
      'register_prompt': "Don't have an account? Register",
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all read',
      'no_notifications': 'No notifications yet',
      'donor_feed': 'Donation Feed',
      'i_can_donate': 'I Can Donate',
      'urgent_request': 'Urgent Request',
      'needs_units': 'Needs @units Units • @component',
      'my_requests': 'My Blood Requests',
      'new_request': 'New Request',
      'create_request_title': 'New Blood Request',
      'blood_type': 'Blood Type',
      'blood_component': 'Blood Component',
      'quantity': 'Quantity (Units)',
      'urgent_checkbox': 'Mark as Urgent Emergency',
      'medical_reason': 'Medical Reason (Optional)',
      'notes': 'Notes (Optional)',
      'submit_request': 'Create Request',
      'request_details': 'Request Details',
      'supporting_docs': 'Supporting Documents',
      'upload': 'Upload',
      'no_docs': 'No documents uploaded yet',
      'qr_scanner': 'Scan Blood Bag QR',
      'point_camera': 'Point camera at the blood bag QR code',
      'bag_status': 'Blood Bag Status',
      'timeline': 'Status Timeline',
      'profile_settings': 'Profile & Settings',
      'eligibility_title': 'Donation Eligibility & History',
      'eligible': 'Eligible to Donate',
      'waiting_period': 'Waiting Period Active',
      'language': 'Language',
      'select_language': 'Select App Language',
      'arabic': 'العربية (Arabic)',
      'english': 'English',
      'logout': 'Logout',
      'waiting_queue_title':
          'Currently Unavailable in Inventory • In Waiting Queue',
      'waiting_queue_desc':
          'No matching stock is available in blood banks, or registered donors have not completed the required 6-month (180-day) recovery period. Your request is active in the live matching queue.',
      'proceed_to_payment': 'Proceed to Payment & Checkout',
    },
    'ar': {
      'app_name': 'لايف لينك (LifeLink)',
      'login_title': 'مرحباً بك مجدداً',
      'login_subtitle': 'سجّل دخولك للمساهمة في إنقاذ الأرواح',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'sign_in': 'تسجيل الدخول',
      'register_prompt': 'ليس لديك حساب؟ أنشئ حساباً الآن',
      'notifications': 'الإشعارات والتنبيهات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'no_notifications': 'لا توجد إشعارات حالياً',
      'donor_feed': 'قائمة طلبات التبرع المتاحة',
      'i_can_donate': 'أنا متاح للتبرع بالدم',
      'urgent_request': 'حالة طارئة وعاجلة',
      'needs_units': 'مطلوب @units أكياس • @component',
      'my_requests': 'طلبات الدم الخاصة بي',
      'new_request': 'طلب دم جديد',
      'create_request_title': 'إنشاء طلب نقل دم جديد',
      'blood_type': 'فصيلة الدم المطلوبة',
      'blood_component': 'مكون الدم (بلازما / صفائح / دم كامل)',
      'quantity': 'الكمية المطلوبة (بالأكياس)',
      'urgent_checkbox': 'تحديد كحالة طارئة حرجة',
      'medical_reason': 'السبب الطبي أو اسم العملية (اختياري)',
      'notes': 'ملاحظات إضافية (اختياري)',
      'submit_request': 'إرسال طلب الدم',
      'request_details': 'تفاصيل ومتابعة الطلب',
      'supporting_docs': 'المستندات والروشتات الطبية',
      'upload': 'رفع ملف / روشتة',
      'no_docs': 'لم يتم رفع مستندات طبية حتى الآن',
      'qr_scanner': 'مسح كود كيس الدم (QR Code)',
      'point_camera': 'وجّه الكاميرا نحو كود الـ QR الموجود على كيس الدم',
      'bag_status': 'حالة وموقع كيس الدم',
      'timeline': 'مراحل التجهيز والتسليم',
      'profile_settings': 'الملف الشخصي والإعدادات',
      'eligibility_title': 'أهلية التبرع وسجل العمليات',
      'eligible': 'مؤهل للتبرع الآن',
      'waiting_period': 'فترة أمان سارية (غير مؤهل حالياً)',
      'language': 'اللغة (Language)',
      'select_language': 'اختر لغة التطبيق',
      'arabic': 'العربية (Arabic)',
      'english': 'English',
      'logout': 'تسجيل الخروج',
      'waiting_queue_title':
          'غير متاح بالمخزون حالياً • قيد المتابعة والانتظار',
      'waiting_queue_desc':
          'لا يتوفر رصيد فوري في بنوك الدم، أو أن المتبرعين لم يتجاوزوا فترة الأمان الطبية الإلزامية (6 أشهر / 180 يوماً). طلبك نشط في قائمة الانتظار.',
      'proceed_to_payment': 'المتابعة إلى الدفع والاستلام',
    }
  };

  static String get(String key, {String locale = 'ar'}) {
    return _localizedValues[locale]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
